server:
  servlet:
    context-path: /sqlite
  port: 18848

spring:
  application:
    name: sqlite
  datasource:
    dynamic:
      primary: db1 # 默认数据源
      datasource:
        db1:
          driver-class-name: org.sqlite.JDBC
          #获取项目存放路径+当前操作系统分隔符+sqlite3+当前操作系统分隔符+数据库文件名
          url: jdbc:sqlite:${user.dir}${file.separator}sqlite3${file.separator}huanbaoducha_db1.db
        db2:
          driver-class-name: org.sqlite.JDBC
          url: jdbc:sqlite:${user.dir}${file.separator}sqlite3${file.separator}huanbaoducha_db2.db

mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID"
      id-type: ASSIGN_ID
  configuration:
    #是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true

# Swagger配置
swagger:
  enabled: true
  title: Spring Boot SQLite
  version: 1.0